### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jxchong** [ReagentX/imessage-exporter#276] opened 2024-06-18 22:12 UTC
Thank you this app is amazing. It works, it's fast, free and OSS. What's not to like!?  Minor addition would be assigning the phone numbers to a name and/or exporting messages with just a single person, but the current approach of dumping everything is fine too.

**Comment by ReagentX** [comment] 2024-06-19 00:59
Thank you for the kind words! Closing this ticket as it is a duplicate of #61 and #62.

**Closed as not planned by ReagentX** 2024-06-19 00:59 UTC
Labels: wontfix
