### ISSUE TITLE
Large conversations truncated during export

### ISSUE THREAD

**Issue by christopher-wong** [ReagentX/imessage-exporter#218] opened 2023-11-28 22:37 UTC
I have a long chat with 2+ years of messages. When I export them, I get the first ~10 months of messages before the results are truncated in the output HTML

This is a recent backup I took on iOS 16 before I upgraded my device to iOS 17.

```
imessage-exporter -f html -p /Users/cwong/Library/Application\ Support/MobileSync/Backup/<BACKUP-ID> -a iOS -c compatible -o backup_export3
```

Using `-f txt` instead shows all messages in the backup.

**Comment by ReagentX** [comment] 2023-11-28 22:47
Given it affects HTML exports only, this is possibly caused by #217.

**Comment by ReagentX** [comment] 2023-11-30 07:51
Do you have any more information on how to replicate? Does this still persist in the current `develop` branch now that #217 was fixed?

**Comment by ReagentX** [comment] 2023-12-04 00:22
Closing this since there are no replication steps or confirmation; feel free to re-open with more context if the issue persists.

**Closed as completed by ReagentX** 2023-12-04 00:22 UTC
Labels: question
